Repository MultiEmail/backend, pull requests merged in 2022-12, with the labels that each got.

#221 feat: auto refresh gmail access token
  src/controllers/mail.controller.ts
  src/models/user.model.ts
Labels: enhancement

#229 fix: added missing page, and size fileld in get all users response
  src/controllers/user.controller.ts
Labels: bug

#235 fix: typegoose error
  src/models/session.model.ts
Labels: bug

#234 feat: new endpoint to get single user
  package.json
  src/controllers/user.controller.ts
  src/routes/admin.routes.ts
  src/schemas/user.schema.ts
  yarn.lock
Labels: bug, enhancement
