Repository MultiEmail/backend, pull requests merged in 2022-10, with the labels that each got.

#25 docs: enabled blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: hacktoberfest-accepted

#28 Added a bot for contributers
  .all-contributorsrc
  package.json
  readme.md
  yarn.lock
Labels: hacktoberfest-accepted

#24 feat: :sparkles: authentication flow
  src/app.ts
  src/controllers/auth.controller.ts
  src/middleware/deserializeUser.middleware.ts
  src/models/user.model.ts
  src/routes/auth.routes.ts
  src/schemas/auth.schema.ts
  src/services/auth.service.ts
  src/services/user.service.ts
  src/utils/email.util.ts
  src/utils/jwt.util.ts
  src/utils/logger.util.ts
  src/utils/otp.util.ts
  src/utils/passport.util.ts
Labels: enhancement, hacktoberfest-accepted

#39 Admin from terminal
  .gitignore
  README.md
  bin/index.ts
  package.json
  src/middleware/authenticateToken.middleware.ts
  src/utils/passport.util.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#26 feat: added username validation
  src/controllers/auth.controller.ts
  src/schemas/auth.schema.ts
Labels: enhancement, hacktoberfest-accepted

#54 docs: :memo: created env example file and updated readme
  .env.example
  README.md
Labels: documentation, hacktoberfest-accepted

#51 chore: Configure eslint
  .eslintrc.js
  .prettierrc
  package.json
  yarn.lock
Labels: hacktoberfest-accepted

#52 feat: :sparkles: Implement middleware to protect admin routes
  src/middleware/checkAdminRole.middleware.ts
Labels: enhancement, hacktoberfest-accepted

#58 Feat: Added support stuff
  src/app.ts
  src/controllers/ticket.controller.ts
  src/middleware/checkAdminRole.middleware.ts
  src/models/ticket.model.ts
  src/routes/ticket.routes.ts
  src/schemas/ticket.schema.ts
  src/services/ticket.service.ts
Labels: enhancement, hacktoberfest-accepted

#50 feat: :sparkles: User logic
  .vscode/settings.json
  README.md
  src/app.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/models/counter.model.ts
  src/models/user.model.ts
  src/routes/user.routes.ts
  src/schemas/user.schema.ts
  src/services/counter.service.ts
  src/services/user.service.ts
  src/utils/jwt.util.ts
Labels: enhancement, hacktoberfest-accepted

#61 feat: :lock: added helmet for security
  README.md
  bin/index.ts
  package.json
  src/app.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#64 feat: :sparkles: routes for support ticket system
  src/app.ts
  src/controllers/ticket.controller.ts
  src/middleware/checkAdminRole.middleware.ts
  src/middleware/requireAdminRole.middleware.ts
  src/models/ticket.model.ts
  src/models/user.model.ts
  src/routes/ticket.routes.ts
  src/schemas/ticket.schema.ts
  src/services/ticket.service.ts
Labels: enhancement, hacktoberfest-accepted

#71 chore: Add husky and conventional commit hook
  .husky/commit-msg
  commitlint.config.js
  package.json
  yarn.lock
Labels: hacktoberfest-accepted

#80 removed acknowledgment
  README.md
Labels: documentation, hacktoberfest-accepted

#81 feat: 🔒 added rate limiter for security
  src/app.ts
  src/middleware/rateLimiter.middleware.ts
  yarn.lock
Labels: security, hacktoberfest-accepted

#82 ci: dockerized the application
  .dockerignore
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  src/app.ts
  src/utils/passport.util.ts
Labels: documentation, enhancement, hacktoberfest-accepted

#83 tests: Wrote Authentication Tests and Minor Adjustment's.
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.controller.ts
  src/schemas/auth.schema.ts
  src/services/user.service.ts
  src/tests/auth.test.js
  yarn.lock
Labels: tests, hacktoberfest-accepted

#92 chore: Wrote test's for /users endpoint
  package.json
  src/tests/auth.test.js
  src/tests/endpoints.test.js
  yarn-error.log
  yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#91 docs: added jsdocs for everything
  src/app.ts
  src/controllers/auth.controller.ts
  src/controllers/ticket.controller.ts
  src/controllers/user.controller.ts
  src/middleware/deserializeUser.middleware.ts
  src/middleware/rateLimiter.middleware.ts
  src/middleware/requireAdminRole.middleware.ts
  src/middleware/validateRequest.middleware.ts
  src/routes/auth.routes.ts
  src/routes/ticket.routes.ts
  src/routes/user.routes.ts
  src/schemas/auth.schema.ts
  src/schemas/ticket.schema.ts
  src/schemas/user.schema.ts
  src/services/auth.service.ts
  src/services/session.service.ts
  src/services/ticket.service.ts
  src/services/user.service.ts
  src/types/enums.ts
  src/types/interfaces.ts
  src/types/types.ts
Labels: documentation, hacktoberfest-accepted

#94 refactor: shifted admin endpoint's to /admin/.. route
  src/app.ts
  src/controllers/admin.controller.ts
  src/controllers/user.controller.ts
  src/routes/admin.routes.ts
  src/routes/user.routes.ts
  src/schemas/admin.schema.ts
  src/schemas/user.schema.ts
  src/tests/endpoints.test.js
Labels: refactor, hacktoberfest-accepted

#98 ci: Add test execution on Pull Request
  .github/workflows/tests.yml
Labels: tests, hacktoberfest-accepted

#107 fix: send error if invalid access token
  src/middleware/deserializeUser.middleware.ts
  src/middleware/requireSameUser.middleware.ts
  src/utils/jwt.util.ts
Labels: bug, hacktoberfest-accepted

#109 feat(env): use EMAIL_SMTP env var
  .env.example
  README.md
  src/utils/email.util.ts
Labels: security, hacktoberfest-accepted

#112 feat: send JWT token in verification email
  .env.example
  README.md
  src/app.ts
  src/controllers/auth.controller.ts
  src/middleware/deserializeUser.middleware.ts
  src/routes/auth.routes.ts
  src/routes/user.routes.ts
  src/schemas/auth.schema.ts
  src/utils/email.util.ts
Labels: enhancement, hacktoberfest-accepted

#116 feat: accept marketing email option at signup
  src/controllers/auth.controller.ts
  src/models/user.model.ts
  src/schemas/auth.schema.ts
Labels: enhancement, hacktoberfest-accepted

#117 feat: user can login using username too
  src/controllers/auth.controller.ts
  src/schemas/auth.schema.ts
Labels: enhancement, hacktoberfest-accepted

#127 feat: google oauth
  .env.example
  README.md
  package.json
  src/app.ts
  src/controllers/auth.controller.ts
  src/models/user.model.ts
  src/routes/auth.routes.ts
  src/routes/user.routes.ts
  src/schemas/auth.schema.ts
  src/services/auth.service.ts
  src/services/user.service.ts
  src/utils/passport.util.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#129 feat: fetch emails from gmail
  bin/index.ts
  src/app.ts
  src/controllers/auth.controller.ts
  src/controllers/mail.controller.ts
  src/models/user.model.ts
  src/routes/mail.routes.ts
  src/schemas/mail.schema.ts
Labels: enhancement, hacktoberfest-accepted

#133 feat: send marketing emails
  src/controllers/marketingEmail.controller.ts
  src/routes/marketingEmail.routes.ts
  src/schemas/marketingEmail.schema.ts
  src/services/marketingEmail.service.ts
Labels: enhancement

#138 feat: pagination while fetching emails from gmail
  src/controllers/mail.controller.ts
  src/schemas/mail.schema.ts
Labels: enhancement, hacktoberfest-accepted

#139 fix: fixing tests
  .github/workflows/tests.yml
  package.json
  src/routes/admin.routes.ts
  src/routes/auth.routes.ts
  src/tests/endpoints.test.js
  src/utils/email.util.ts
Labels: tests, hacktoberfest-accepted

#140 fix: validation for multiple google accounts
  src/controllers/auth.controller.ts
Labels: bug, hacktoberfest-accepted

#146 feat: mark user as admin
  src/controllers/admin.controller.ts
  src/controllers/user.controller.ts
  src/routes/admin.routes.ts
  src/schemas/admin.schema.ts
  src/tests/endpoints.test.js
Labels: hacktoberfest-accepted

#144 refactor: refactored logic for sending marketing email
  src/app.ts
  src/controllers/admin.controller.ts
  src/controllers/marketingEmail.controller.ts
  src/models/marketingEmail.model.ts
  src/routes/admin.routes.ts
  src/routes/marketingEmail.routes.ts
  src/schemas/marketingEmail.schema.ts
  src/services/marketingEmail.service.ts
Labels: refactor, hacktoberfest-accepted

#162 refactor: move admin controller to user controller
  src/controllers/admin.controller.ts
  src/controllers/user.controller.ts
  src/routes/admin.routes.ts
Labels: refactor, hacktoberfest-accepted

#163 feat: fetch all marketing emails
  src/controllers/marketingEmail.controller.ts
  src/routes/admin.routes.ts
  src/services/marketingEmail.service.ts
Labels: enhancement, hacktoberfest-accepted

#165 feat: pagination for get all users
  src/controllers/user.controller.ts
  src/routes/admin.routes.ts
  src/schemas/admin.schema.ts
Labels: enhancement, hacktoberfest-accepted

#149 fix: fixed spelling in README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#169 refactor!: changed case conventions in database
  bin/index.ts
  src/controllers/auth.controller.ts
  src/controllers/marketingEmail.controller.ts
  src/models/user.model.ts
  src/services/user.service.ts
  src/tests/endpoints.test.js
Labels: refactor, hacktoberfest-accepted

#176 feat: added option toget users who have receive marketing emails as true
  src/controllers/user.controller.ts
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#173 feat: send email from gmail account
  .vscode/settings.json
  package.json
  src/app.ts
  src/controllers/auth.controller.ts
  src/controllers/mail.controller.ts
  src/middleware/getCurrentConnectedService.middleware.ts
  src/routes/mail.routes.ts
  src/schemas/mail.schema.ts
  yarn.lock
Labels: enhancement

#171 feat: fetch single message from gmail API
  src/controllers/auth.controller.ts
  src/controllers/mail.controller.ts
  src/routes/auth.routes.ts
  src/routes/mail.routes.ts
  src/schemas/auth.schema.ts
  src/schemas/mail.schema.ts
  src/services/auth.service.ts
Labels: enhancement

#181 fix: docker yarn run issues + cache
  Dockerfile
  docker-compose.yml
Labels: fixed

#184 feat: get drafts from gmail
  src/controllers/mail.controller.ts
  src/routes/mail.routes.ts
  src/schemas/mail.schema.ts
Labels: enhancement
